services:
  db:
    image: pgvector/pgvector:pg16
    container_name: poessa_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - poessa_pgdata:/var/lib/postgresql/data

volumes:
  poessa_pgdata: